language: php

php:
  - '7.0'
  - '7.1'

# Install test coverage package.
install:
  - composer require squizlabs/php_codesniffer
  - composer require satooshi/php-coveralls

# Install packages and create test coverage log directory.
before_script:
  - composer install --dev --no-interaction
  - mkdir -p build/logs

# Run tests and generate test coverage report.
script:
  - vendor/bin/phpcs ./src ./tests --extensions=php --standard=PSR2
  - phpunit -d usps_user_id=$USPS_USER_ID -d easypost_api_key=$EASYPOST_API_KEY --coverage-clover build/logs/clover.xml

# Submit test coverage report to Coveralls.
after_success:
  - vendor/bin/coveralls -v

# Cache composer bits for faster test suite runs.
cache:
  directories:
  - $HOME/.composer/cache

notifications:
  email:
    on_success: change
    on_failure: always
